import {
  TbBrandReact,
  TbBrandCss3,
  TbBrandReactNative,
  TbApi,
  TbBrandVite,
  TbBrandFramerMotion,
} from "react-icons/tb";
import {
  SiRedux,
  SiNextdotjs,
  SiJest,
  SiGraphql,
  SiTestinglibrary,
  SiMui,
  SiMaterialdesign,
  SiMysql,
  SiRedis,
  SiNginx,
  SiDocker,
  SiGithubactions,
  SiNpm,
  SiReactbootstrap,
  SiJsonwebtokens,
  SiVitest,
  SiPm2,
  SiDrizzle,
  SiSupabase,
  SiExpress,
  SiMongodb,
  SiTailwindcss,
  SiTypescript,
  SiPostgresql,
  SiMantine,
  SiPostcss,
  SiMedusa,
  SiTurborepo,
  SiLeaflet,
  SiSwiper,
  SiPrisma,
  SiShadcnui,
  SiRemix,
  SiJavascript,
} from "react-icons/si";
import { FaSass, FaShopify, FaYarn, FaBootstrap, FaMap } from "react-icons/fa6";
import { FaNodeJs, FaMailBulk } from "react-icons/fa";

export const icons: Record<string, React.ElementType> = {
  shopify: FaShopify,
  medusa: SiMedusa,
  api: TbApi,
  vite: TbBrandVite,
  "react-bootstrap": SiReactbootstrap,
  typescript: SiTypescript,
  javascript: SiJavascript,
  react: TbBrandReact,
  redux: SiRedux,
  next: SiNextdotjs,
  jest: SiJest,
  graphql: SiGraphql,
  "react-native": TbBrandReactNative,
  "testing-library": SiTestinglibrary,
  vitest: SiVitest,
  css: TbBrandCss3,
  postcss: SiPostcss,
  mui: SiMui,
  "material-design": SiMaterialdesign,
  mantine: SiMantine,
  bootstrap: FaBootstrap,
  tailwind: SiTailwindcss,
  sass: FaSass,
  "framer-motion": TbBrandFramerMotion,
  shadcn: SiShadcnui,
  postgresql: SiPostgresql,
  mysql: SiMysql,
  mongodb: SiMongodb,
  redis: SiRedis,
  node: FaNodeJs,
  jwt: SiJsonwebtokens,
  express: SiExpress,
  drizzle: SiDrizzle,
  supabase: SiSupabase,
  turborepo: SiTurborepo,
  nginx: SiNginx,
  docker: SiDocker,
  "git-actions": SiGithubactions,
  prisma: SiPrisma,
  npm: SiNpm,
  yarn: FaYarn,
  pm2: SiPm2,
  leaflet: SiLeaflet,
  nodemailer: FaMailBulk,
  map: FaMap,
  swiper: SiSwiper,
  remix: SiRemix,
};
